theme = "coder"
baseURL = "https://abhipray.com/"
languageCode = "en-us"
title = "embedded sigproc"

paginate = 20
relativeURLs = true
markup = "mmark"
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
publishDir = "docs"
disqusShortname = "embedded-sigproc"
googleAnalytics = "UA-127997927-1"
canonifyurls = false

[params]
    author = "Abhipray Sahoo"
    info = "Engineer@Neosensory - Student@Stanford"
    description = "Journal"
    keywords = "audio, embedded systems, signal processing"
    avatarurl = "images/Abhi.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/abhipray/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/abhipray42/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/abhipray-sahoo-92b9b13a/"    

# Menu links
[[menu.main]]
    name = "Posts"
    weight = 1
    url  = "/posts/"